CREATE DATABASE escola_db;

CREATE TABLE alunos (
    id INT(11) NOT NULL AUTO_INCREMENT,
    nome VARCHAR(80) DEFAULT NULL,
    cpf CHAR(11) DEFAULT NULL,
    cep CHAR(8) DEFAULT NULL,
    uf CHAR(2) DEFAULT NULL,
    rua VARCHAR(120) DEFAULT NULL,
    numero INT(11) DEFAULT NULL,
    complemento VARCHAR(120) DEFAULT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);